import {
  CircleDashedIcon,
  PencilSimpleIcon,
  ListIcon,
  CheckSquareIcon,
  ToggleLeftIcon,
  RadioButtonIcon,
  TableIcon,
  FilesIcon,
  ChatCircleIcon,
  SidebarSimpleIcon,
  TabsIcon,
  FolderOpenIcon,
  LightbulbIcon,
  BalloonIcon,
  TagIcon,
  BookmarkIcon,
  UserIcon,
  HourglassIcon,
  GearIcon,
  TrendUpIcon,
  CalendarIcon,
  MagnifyingGlassIcon,
  BellIcon,
  CaretCircleDownIcon,
  AtomIcon,
  SpinnerGapIcon,
  TextboxIcon,
  TextAaIcon,
  ArrowUpIcon,
  SunIcon,
  SquareIcon,
  LayoutIcon,
  GlobeIcon,
  WifiHighIcon,
  TranslateIcon,
  FlaskIcon,
  TableIcon as PluginTableIcon,
  CloudIcon,
} from '@phosphor-icons/react';

const Constants = {
  componentList: [
    {
      name: 'Accordion',
      description: 'Collapsible content sections with smooth animations',
      Icon: FolderOpenIcon,
      path: '/components/accordion',
      category: 'Layout',
    },
    {
      name: 'Avatar',
      description: 'User profile pictures and placeholder images',
      Icon: UserIcon,
      path: '/components/avatar',
      category: 'Display',
    },
    {
      name: 'Badge',
      description: 'Small status indicators and notification counters',
      Icon: TagIcon,
      path: '/components/badge',
      category: 'Display',
    },
    {
      name: 'Button',
      description: 'Versatile button component with multiple variants',
      Icon: CircleDashedIcon,
      path: '/components/button',
      category: 'Input',
      isShowHome: true,
    },
    {
      name: 'Checkbox',
      description: 'Customizable checkbox with labels and states',
      Icon: CheckSquareIcon,
      path: '/components/checkbox',
      category: 'Input',
      isShowHome: true,
    },
    {
      name: 'Chip',
      description: 'Compact elements for tags, filters and selections',
      Icon: BookmarkIcon,
      path: '/components/chip',
      category: 'Display',
    },
    {
      name: 'Date Picker',
      description: 'Calendar-based date selection component',
      Icon: CalendarIcon,
      path: '/components/date-picker',
      category: 'Input',
      isShowHome: true,
    },
    {
      name: 'Dialog',
      description: 'Modal dialog for important user interactions',
      Icon: ChatCircleIcon,
      path: '/components/dialog',
      category: 'Overlay',
    },
    {
      name: 'Drawer',
      description: 'Sliding panel from screen edges',
      Icon: SidebarSimpleIcon,
      path: '/components/drawer',
      category: 'Overlay',
    },
    {
      name: 'Dropdown',
      description: 'Dropdown menu with actions and options',
      Icon: CaretCircleDownIcon,
      path: '/components/dropdown',
      category: 'Overlay',
    },
    {
      name: 'Information Status',
      description: 'Status messages and alerts for users',
      Icon: AtomIcon,
      path: '/components/information-status',
      category: 'Feedback',
    },
    {
      name: 'Loader',
      description: 'Loading indicators and progress spinners',
      Icon: GearIcon,
      path: '/components/loader',
      category: 'Feedback',
    },
    {
      name: 'Loading Linear',
      description: 'Loading indicators and progress linears',
      Icon: HourglassIcon,
      path: '/components/loading-linear',
      category: 'Feedback',
    },
    {
      name: 'Loading Spinner',
      description: 'Loading indicators and progress spinners',
      Icon: SpinnerGapIcon,
      path: '/components/loading-spinner',
      category: 'Feedback',
    },
    {
      name: 'Notification',
      description: 'Toast notifications and system alerts',
      Icon: BellIcon,
      path: '/components/notification',
      category: 'Feedback',
      isShowHome: true,
    },
    {
      name: 'Pagination',
      description: 'Navigate through data pages efficiently',
      Icon: FilesIcon,
      path: '/components/pagination',
      category: 'Navigation',
    },
    {
      name: 'Popover',
      description: 'Floating content containers with positioning',
      Icon: BalloonIcon,
      path: '/components/popover',
      category: 'Overlay',
    },
    {
      name: 'Progress Bar',
      description: 'Visual progress indicators and loaders',
      Icon: TrendUpIcon,
      path: '/components/progress-bar',
      category: 'Feedback',
    },
    {
      name: 'Radio Button',
      description: 'Radio button groups for single selection',
      Icon: RadioButtonIcon,
      path: '/components/radio-button',
      category: 'Input',
    },
    {
      name: 'Search Field',
      description: 'Search input with suggestions and filtering',
      Icon: MagnifyingGlassIcon,
      path: '/components/search-field',
      category: 'Input',
    },
    {
      name: 'Select',
      description: 'Dropdown selection with search capability',
      Icon: ListIcon,
      path: '/components/select',
      category: 'Input',
      isShowHome: true,
    },
    {
      name: 'Sidebar',
      description: 'Collapsible navigation sidebar component',
      Icon: SidebarSimpleIcon,
      path: '/components/sidebar',
      category: 'Navigation',
    },
    {
      name: 'Skeleton',
      description: 'Loading placeholders for content',
      Icon: HourglassIcon,
      path: '/components/skeleton',
      category: 'Feedback',
      isShowHome: true,
    },
    {
      name: 'Switch',
      description: 'Toggle switch for binary choices',
      Icon: ToggleLeftIcon,
      path: '/components/switch',
      category: 'Input',
      isShowHome: true,
    },
    {
      name: 'Table',
      description: 'Feature-rich data table with sorting',
      Icon: TableIcon,
      path: '/components/table',
      category: 'Display',
    },
    {
      name: 'Tabs',
      description: 'Organize content in tabbed interface',
      Icon: TabsIcon,
      path: '/components/tabs',
      category: 'Navigation',
    },
    {
      name: 'Text Field',
      description: 'Text input with validation and styles',
      Icon: PencilSimpleIcon,
      path: '/components/text-field',
      category: 'Input',
      isShowHome: true,
    },
    {
      name: 'Tooltip',
      description: 'Contextual information on hover',
      Icon: LightbulbIcon,
      path: '/components/tooltip',
      category: 'Overlay',
    },
    // {
    //   name: 'Image Hover Effect',
    //   description: 'Animated image hover effects',
    //   Icon: ImageIcon,
    //   path: '/components/image-hover-effect',
    //   category: 'Display',
    // },
    {
      name: 'Theme Mode Toggle',
      description: 'Toggle between light and dark themes',
      Icon: SunIcon,
      path: '/components/theme-mode-toggle',
      category: 'Display',
    },
    {
      name: 'Calendar',
      description: 'Interactive calendar component for date selection',
      Icon: SquareIcon,
      path: '/components/calendar',
      category: 'Display',
    },
    {
      name: 'Container',
      description: 'A responsive container component for layout',
      Icon: LayoutIcon,
      path: '/components/container',
      category: 'Layout',
    },
    {
      name: 'Input',
      description: 'A flexible input component with multiple variants, sizes, and icon support',
      Icon: TextboxIcon,
      path: '/components/input',
      category: 'Input',
    },
    {
      name: 'Label',
      description: 'A versatile label component for form elements and UI',
      Icon: TextAaIcon,
      path: '/components/label',
      category: 'Display',
    },
    {
      name: 'Back to Top Button',
      description: 'A button that allows users to quickly scroll back to the top of the page',
      Icon: ArrowUpIcon,
      path: '/components/back-to-top-button',
      category: 'Navigation',
      isNew: true,
    },
    {
      name: 'Language Select',
      description: 'Dropdown for switching application language / locale',
      Icon: GlobeIcon,
      path: '/components/language-select',
      category: 'Navigation',
      isNew: true,
    },
    {
      name: 'Language Toggle',
      description: 'Toggle for switching application language / locale',
      Icon: GlobeIcon,
      path: '/components/language-toggle',
      category: 'Navigation',
      isNew: true,
    },
  ],
  pluginList: [
    {
      name: 'Axios',
      description:
        'Axios instance, interceptors, token yönetimi, AuthContext/AuthProvider ve createService kalıbı',
      Icon: CloudIcon,
      path: '/plugins/axios',
      registryKey: 'plugin-axios',
    },
    {
      name: 'Forms',
      description:
        "Formik + Yup entegrasyonu, TRA UI Kit'e bağlı form bileşenleri ve Validations sabitleri",
      Icon: FlaskIcon,
      path: '/plugins/forms',
      registryKey: 'plugin-forms',
    },
    {
      name: 'i18n',
      description:
        'inlang/paraglide ile compile-time tip-güvenli çeviriler, LocaleContext ve dil değiştirici',
      Icon: TranslateIcon,
      path: '/plugins/i18n',
      registryKey: 'plugin-i18n',
    },
    {
      name: 'SignalR',
      description:
        "Microsoft SignalR HubConnection, otomatik yeniden bağlantı, MessageHubContext ve hook'lar",
      Icon: WifiHighIcon,
      path: '/plugins/signalr',
      registryKey: 'plugin-signalr',
    },
    {
      name: 'Table',
      description:
        'TanStack Table v8 wrapper – sıralama, filtreleme, sayfalama, dışa aktarma ve skeleton desteği',
      Icon: PluginTableIcon,
      path: '/plugins/table',
      registryKey: 'plugin-table',
    },
  ],
};

export default Constants;
